# Generated by Django 2.2.3 on 2020-08-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='qualification_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='qualification_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='semester_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='semester_2',
        ),
    ]
