# Generated by Django 2.2.3 on 2020-08-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200828_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='num_rd',
        ),
        migrations.AddField(
            model_name='project',
            name='course_initial',
            field=models.CharField(blank=True, choices=[('TESIS_1', 'TESIS_1'), ('TESIS_2', 'TESIS_2')], max_length=40, null=True, verbose_name='Curso de Inicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_doc_support',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolucion Decanal'),
        ),
        migrations.AddField(
            model_name='project',
            name='num_doc_support',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de Resolucion Decanal'),
        ),
    ]
