# Generated by Django 2.2.3 on 2020-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20200831_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_doc_support',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Resolucion Decanal'),
        ),
    ]
