# Generated by Django 2.2.3 on 2020-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200831_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='grade',
            field=models.CharField(blank=True, choices=[('PREGRADO', 'PREGRADO'), ('POSGRADO', 'POSGRADO')], max_length=50, null=True, verbose_name='Grado'),
        ),
    ]
