# Generated by Django 2.2.3 on 2020-09-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodAcademic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Periodo Academico',
                'verbose_name_plural': 'Periodos Academicos',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='period_academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyects', to='projects.PeriodAcademic'),
        ),
    ]
