# Generated by Django 2.2.3 on 2020-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo de Escuela')),
                ('code_faculty', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo de Facultad')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Escuela')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
    ]
