# Generated by Django 2.2.3 on 2020-08-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qualification_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificacion Semestre 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificacion Semestre 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_1',
            field=models.BooleanField(default=False, verbose_name='Termino Semestre 1?'),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_2',
            field=models.BooleanField(default=False, verbose_name='Termino Semestre 2?'),
        ),
    ]
