# Generated by Django 2.2.3 on 2020-09-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0004_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='asesor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
